language: node_js

cache: yarn
directories:
    - node_modules
install:
    - yarn install

script:
    - yarn test
    - yarn run build

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: build
    on:
        branch: main
